<?php

namespace App\Services;

use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Storage;

class DvlaDriverService
{
    private string $baseUrl = 'https://driver-vehicle-licensing.api.gov.uk/driver-enquiry/v1/driving-licences';

    /**
     * Lookup driver details using check code
     * 
     * Note: Driver Data API requires:
     * - Check code (generated by driver on gov.uk)
     * - Driver's last name
     * - Last 8 characters of driving licence number
     */
    public function lookup(string $checkCode, string $lastName, string $licenceNumber): ?array
    {
        // Normalize inputs - keep check code case sensitive
        $checkCode = str_replace(' ', '', trim($checkCode));
        $lastName = trim($lastName);
        $licenceNumber = strtoupper(str_replace(' ', '', trim($licenceNumber)));

        // Get last 8 chars of licence number
        $last8 = substr($licenceNumber, -8);

        if (empty($checkCode) || empty($lastName) || strlen($last8) < 8) {
            return null;
        }

        try {
            $response = Http::withHeaders([
                'Content-Type' => 'application/json',
            ])->post($this->baseUrl, [
                'checkCode' => $checkCode,
                'lastName' => $lastName,
                'licenceNumber' => $last8,
            ]);

            if ($response->successful()) {
                $data = $response->json();
                return $this->mapToDriverFields($data);
            }

            Log::warning('DVLA Driver API error', [
                'status' => $response->status(),
                'body' => $response->json(),
            ]);

            return null;

        } catch (\Exception $e) {
            Log::error('DVLA Driver API exception', [
                'error' => $e->getMessage(),
            ]);
            return null;
        }
    }

    /**
     * Map DVLA response to our database fields
     */
    private function mapToDriverFields(array $data): array
    {
        $entitlements = [];
        if (isset($data['entitlements']) && is_array($data['entitlements'])) {
            foreach ($data['entitlements'] as $ent) {
                $entitlements[] = [
                    'code' => $ent['code'] ?? null,
                    'validFrom' => $ent['validFrom'] ?? null,
                    'validTo' => $ent['validTo'] ?? null,
                    'type' => $ent['type'] ?? null,
                ];
            }
        }

        // Calculate total penalty points
        $penaltyPoints = 0;
        if (isset($data['penaltyPoints']) && is_array($data['penaltyPoints'])) {
            foreach ($data['penaltyPoints'] as $pp) {
                $penaltyPoints += (int)($pp['points'] ?? 0);
            }
        }

        // Get disqualification end date if any
        $disqualifiedUntil = null;
        if (isset($data['disqualifications']) && is_array($data['disqualifications'])) {
            foreach ($data['disqualifications'] as $disq) {
                if (isset($disq['endDate'])) {
                    // Get the latest disqualification end date
                    if (!$disqualifiedUntil || $disq['endDate'] > $disqualifiedUntil) {
                        $disqualifiedUntil = $disq['endDate'];
                    }
                }
            }
        }

        // Extract main licence category codes as string
        $licenceTypes = [];
        foreach ($entitlements as $ent) {
            if (!empty($ent['code'])) {
                $licenceTypes[] = $ent['code'];
            }
        }

        return [
            'license_number' => $data['drivingLicenceNumber'] ?? null,
            'license_status' => $data['status'] ?? 'unknown',
            'license_issue_date' => $data['issueDate'] ?? null,
            'license_expiry_date' => $data['expiryDate'] ?? null,
            'license_type' => implode(', ', array_unique($licenceTypes)),
            'penalty_points' => $penaltyPoints,
            'disqualified_until' => $disqualifiedUntil,
            'entitlements' => $entitlements,
            
            // Personal info if available
            'name' => trim(($data['firstName'] ?? '') . ' ' . ($data['lastName'] ?? '')),
            'date_of_birth' => $data['dateOfBirth'] ?? null,
            'address' => $this->formatAddress($data['address'] ?? null),
            
            // Photo URL if available
            'photo_url' => $data['photoUrl'] ?? null,
            
            // Raw data for reference
            '_raw' => $data,
        ];
    }

    /**
     * Format address array to string
     */
    private function formatAddress(?array $address): ?string
    {
        if (!$address) {
            return null;
        }

        $parts = array_filter([
            $address['line1'] ?? null,
            $address['line2'] ?? null,
            $address['line3'] ?? null,
            $address['postTown'] ?? null,
            $address['postcode'] ?? null,
        ]);

        return implode(', ', $parts) ?: null;
    }

    /**
     * Download and save driver photo
     */
    public function savePhoto(string $photoUrl, int $driverId): ?string
    {
        try {
            $response = Http::get($photoUrl);
            
            if ($response->successful()) {
                $extension = 'jpg'; // Default
                $contentType = $response->header('Content-Type');
                
                if (str_contains($contentType, 'png')) {
                    $extension = 'png';
                }

                $filename = "drivers/{$driverId}/photo.{$extension}";
                
                Storage::disk('public')->put($filename, $response->body());
                
                return $filename;
            }
        } catch (\Exception $e) {
            Log::error('Failed to save driver photo', [
                'driver_id' => $driverId,
                'error' => $e->getMessage(),
            ]);
        }

        return null;
    }
}
